#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Portfolion\Console\Application;

// Create the application
$application = new Application();

// Run the console application
$application->run();
